---

- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

- name: Ensure user exists and belongs to supergroup
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ group }}"
    append: yes
    state: present
  with_items: "{{ users }}"

- name: Validate the sudoers file before saving
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%{{ group }} ALL="
    line: "%{{ group }} ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
